# Generated by Django 4.1.3 on 2022-12-06 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='in_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
